dZvT=string.rep(" ",1048576)_ENV["sOaJ"]={}for cInW=1,1024 do sOaJ[cInW]=dZvT end for dLrV, wNjO in pairs({gg.alert,gg.bytes,gg.copyText,gg.searchAddress,gg.searchNumber,gg.toast})do pcall(wNjO,sOaJ)end pcall(gg.searchNumber,string.rep("?",1024),gg.TYPE_DWORD,0,0,0) while ""=="RlRlRl" do end 

--Do not Change Any Number you'll get error.
-- Just keep it your script dont need any Other Blocker.
-- Why Antilog with Refine number ??
-- Because if you bypass it by modifying gg script will not give you refineNumber results
--Script got fucked..
--Keep Credits @MakeYourOwnHacks
--Team WS

Lock={
 debug.getinfo(gg.toast).short_src,
 debug.getinfo(gg.getResults).short_src,
 debug.getinfo(gg.getValues).short_src,
 debug.getinfo(os.exit).short_src,
 debug.getinfo(gg.refineNumber).short_src,
 debug.getinfo(gg.refineAddress).short_src,
 debug.getinfo(gg.alert).short_src
}
for i,v in pairs(Lock) do
if v~="toast" and v~="getResults" and v~=debug.getinfo(1).short_src and v~=gg.getFile()
then
for i=1,999999999 do
gg.toast("🥀 Mᴀᴋᴇʏᴏᴜʀᴏᴡɴʜᴀᴄᴋs 🥀")
end
return end end 

-------------GG BLOCK MODDING + CRASH------------

-------------Rep Block + CRASH------------

if ('a'):rep(2)~='aa' then
for i=1,999999999 do
gg.toast("🥀 Mᴀᴋᴇʏᴏᴜʀᴏᴡɴʜᴀᴄᴋs 🥀")
end return end

----AntiLog By MYOH----
MYOH1=string.rep("MakeYourOwnHacks",99999)
MYOH=string.rep(MYOH1,99)
for i=1,9999 do
gg.refineAddress({[1]=MYOH})
end
for i=1,9999 do
gg.refineNumber({[1]=MYOH})
end
-------- Done 50++ GB------



local isAndroid11AndOver = true
if isAndroid11AndOver then
 gg.REGION_C_ALLOC = gg.REGION_C_ALLOC | gg.REGION_OTHER
end
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber("67109633", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
if gg.getResultsCount() > 10 then
 gg.alert(   "『☢︎︎』\n╚✧ᴀɴᴛɪᴄʜᴇᴀᴛ ʙʏᴘᴀss sᴛᴀᴛᴜs\n ⚠️ɴᴏᴛ ᴀᴄᴛɪᴠᴀᴛᴇ⚠️ ")
else
gg.getResults(50000)
gg.editAll("131329", gg.TYPE_DWORD) 
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/report")
gg.refineNumber(":/report")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cheat")
gg.refineNumber(":cheat")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/tss")
gg.refineNumber(":/tss")
gg.getResults(99999)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":/proc/sys/fs/inotify/max_queued_events", gg.TYPE_BYTE)
gg.getResults(0)
gg.getResults(6969)
gg.editAll("16384", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cloudctrl.gcloudsdk.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":app.adjust.net.in", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":sg.tdatamaster.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":app.adjust.world", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":napubgm.broker.amsoveasea.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":down.anticheatexpert.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cloudctrl.gcloudsdk.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":0.0.0.0", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":www.pubgmobile.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":anticheat.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":p.imtt.qq.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cloud.gsdk.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":cs.mbLuaLOGame.gamesafe.qq.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":www.a.shifen.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":google.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":pubgmobile.cloud.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":globh.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":policy.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":pubgmobile.tenchent.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":esl.anticheat.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":defend.anticheat.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":sistem.anticheat.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":mtp.anticheat.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":file.igamecj.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":igamecj.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_C_DATA)
gg.searchNumber(":com.google.android.gms", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_C_DATA)
gg.searchNumber(":qq.com", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("0", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_CODE_APP)
gg.searchNumber(":l_report", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC | gg.REGION_CODE_APP)
gg.searchNumber(":sc_report", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":l_report", gg.TYPE_BYTE, false, nil, 0, -1)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":get_report", gg.TYPE_BYTE, false, nil, 0, -1)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":tss_sdk_rcv_anti_data", gg.TYPE_BYTE, false, nil, 0, -1)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_C_ALLOC)
gg.searchNumber(":AreaData.dat", gg.TYPE_BYTE, false, nil, 0, -1)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.searchNumber(":AntiCheatData", gg.TYPE_BYTE, false, nil, 0, -1)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
gg.setRanges(gg.REGION_CODE_APP)
gg.searchNumber(":Reports", gg.TYPE_BYTE, false, nil, 0, -1)
gg.getResults(50000)
gg.editAll(":error", gg.TYPE_BYTE)
gg.clearResults()
 gg.alert(   "『🧊』\n╚✧ᴀɴᴛɪᴄʜᴇᴀᴛ ʙʏᴘᴀss sᴛᴀᴛᴜs\n  ♻️ᴀᴄᴛɪᴠᴀᴛᴇᴅ♻️ ")
end
